name: oppish_translator
description: Translation app to and from Oppish.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  flutter_tts: 0.9.0
  speech_to_text: 1.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
